language: kotlin
sudo: required
dist: trusty

jdk:
  - oraclejdk8

stages:
  - run-ank
#  - deploy
  - deploy-docs

before_install:
  - sudo pip install --upgrade pip
  - sudo pip install pyOpenSSL ndg-httpsclient pyasn1
  - sudo pip install awscli --force-reinstall --upgrade
  - export PATH=~/.local/bin:$PATH
  - mkdir -p ~/$TRAVIS_BUILD_NUMBER
  - mkdir -p ~/SITE
  - aws s3 sync s3://S3_BUCKET ~/SITE
  - aws s3 sync s3://S3_BUCKET/$TRAVIS_BUILD_NUMBER modules/docs/arrow-docs/build

jobs:
  include:
  - stage: run-ank
    script:
    - ./gradlew clean build
    - ./gradlew dokka :arrow-docs:runAnk
#  - stage: deploy
#    script:
#    - ./gradlew codeCoverageReport
#    - bash <(curl -s https://codecov.io/bash)
#    - ./deploy-scripts/deploy.sh
  - stage: deploy-docs
    script:
    - rvm use 2.5.3 --install --fuzzy
    - gem install jekyll -v 3.7.4
    - jekyll build -s ~/$TRAVIS_BUILD_NUMBER/site/ -d ~/SITE
    - aws s3 rm --recursive s3://S3_BUCKET/$TRAVIS_BUILD_NUMBER # clean up after ourselves
