sudo: required

services:
  - docker

install:
 - sudo apt-get update
 - docker version
 - sudo pip install docker-compose
 - base=https://github.com/docker/machine/releases/download/v0.14.0 &&
     curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
     sudo install /tmp/docker-machine /usr/local/bin/docker-machine
 - docker-compose version
 - docker-machine version

before_script:
 - sudo service mysql stop
 - sh ./gradlew ::copyKotlinLibs
 - sh ./gradlew war
 - mkdir ./docker/frontend/war/
 - mkdir ./docker/backend/war/
 - cp ./kotlin.web.demo.server/build/libs/WebDemoWar.war ./docker/frontend/war/WebDemoWar.war
 - cp ./kotlin.web.demo.backend/build/libs/WebDemoBackend.war ./docker/backend/war/WebDemoBackend.war
 - docker-machine provision aws01
 - docker-machine env aws01
 - eval $(docker-machine env aws01)
 - docker-compose build
 - docker-compose up