language: kotlin
sudo: required
dist: trusty

jdk:
  - oraclejdk8

stages:
  - run-ank
#  - deploy
  - build-docs
  - deploy-docs

jobs:
  include:
  - stage: run-ank
    script:
    - ./gradlew clean build
    - ./gradlew dokka :arrow-docs:runAnk
#  - stage: deploy
#    script:
#    - ./gradlew codeCoverageReport
#    - bash <(curl -s https://codecov.io/bash)
#    - ./deploy-scripts/deploy.sh
  - stage: build-docs
    script:
    - rvm use 2.5.3 --install --fuzzy
    - gem install jekyll -v 3.7.4
    - jekyll build -s modules/docs/arrow-docs/build/site/ -d modules/docs/arrow-docs/build/_site
  - stage: deploy-docs
    script: skip
    deploy:
      provider: s3
      access_key_id: $S3_ACCESS_KEY_ID
      secret_access_key: $S3_SECRET_ACCESS_KEY
      bucket: $S3_BUCKET
      skip_cleanup: true
      local_dir: modules/docs/arrow-docs/build/_site
      on:
        branch: master
