language: kotlin
sudo: required
dist: trusty

jdk:
  - oraclejdk8

stages:
  - run-ank
#  - deploy
  - deploy-docs

env:
  global:
  # include $HOME/.local/bin for `aws`
  - PATH=$HOME/.local/bin:$PATH

before_install:
  - sudo pip install --upgrade pip
  - sudo pip uninstall awscli
  - sudo pip install pyOpenSSL ndg-httpsclient pyasn1
  - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
  - unzip awscli-bundle.zip
  - ./awscli-bundle/install -b ~/bin/aws
  - echo $PATH | grep ~/bin
  - export PATH=~/bin:$PATH
  - mkdir -p ~/site
  - aws s3 sync ~/SITE s3://$S3_BUCKET

jobs:
  include:
  - stage: run-ank
    script:
    - ./gradlew clean build
    - ./gradlew dokka :arrow-docs:runAnk
    - aws s3 sync modules/docs/arrow-docs/build/site s3://$S3_BUCKET/$TRAVIS_BUILD_NUMBER/site
#  - stage: deploy
#    script:
#    - ./gradlew codeCoverageReport
#    - bash <(curl -s https://codecov.io/bash)
#    - ./deploy-scripts/deploy.sh
  - stage: deploy-docs
    script:
    - rvm use 2.5.3 --install --fuzzy
    - gem install jekyll -v 3.7.4
    - aws s3 sync s3://$S3_BUCKET/$TRAVIS_BUILD_NUMBER/site ~/site
    - jekyll build -s ~/site -d ~/_site
    - aws s3 _site s3://$S3_BUCKET
    - aws s3 rm --recursive s3://$S3_BUCKET/$TRAVIS_BUILD_NUMBER # clean up after ourselves
