sudo: required
dist: trusty

services:
  - docker

install:
 - sudo apt-get update
 - docker version
 - sudo pip install docker-compose
 - base=https://github.com/docker/machine/releases/download/v0.14.0 &&
     curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
     sudo install /tmp/docker-machine /usr/local/bin/docker-machine
 - docker-compose version
 - docker-machine version

before_script:
 - sudo service mysql stop
 - chmod +x deploy.sh

script:
 - sh ./gradlew ::copyKotlinLibs
 - sh ./gradlew war
 - mkdir ./docker/frontend/war/
 - mkdir ./docker/backend/war/
 - cp ./kotlin.web.demo.server/build/libs/WebDemoWar.war ./docker/frontend/war/WebDemoWar.war
 - cp ./kotlin.web.demo.backend/build/libs/WebDemoBackend.war ./docker/backend/war/WebDemoBackend.war
 - docker-machine create --driver none --url=tcp://107.23.241.80:2376 trykotlinweb
 - docker-machine ls
 - docker-machine regenerate-certs -f trykotlinweb
 - docker-machine env trykotlinweb
 - eval $(docker-machine env trykotlinweb)
 - docker-compose build
 - docker-compose up
