sudo: required
dist: trusty

services:
  - docker

install:
 - sudo apt-get update
 - docker version
 - sudo pip install docker-compose
 - base=https://github.com/docker/machine/releases/download/v0.14.0 &&
     curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine &&
     sudo install /tmp/docker-machine /usr/local/bin/docker-machine
 - docker-compose version
 - docker-machine version

before_script:
 - sh ./gradlew ::copyKotlinLibs
 - sh ./gradlew war
 - chmod +x deploy.sh
 - pwd
 - ls
 - ls docker/frontend/war/

script:
 - sudo sh deploy.sh aws01