before_script:
- openssl aes-256-cbc -pass "pass:$TRAVIS_CI_SECRET" -in ./.secret -out ./trykotlinwebdemo.pem -d -a
- chmod 400 ./trykotlinwebdemo.pem

script:
- ssh -o "StrictHostKeyChecking no" -q -i ./trykotlinwebdemo.pem $EC2 'cd kotlin-web-demo; sh deploy.sh; exit'