language: kotlin
sudo: required
dist: trusty

jdk:
  - oraclejdk8

stages:
  - run-ank
#  - deploy
  - deploy-docs

env:
  global:
  # include $HOME/.local/bin for `aws`
  - PATH=$HOME/.local/bin:$PATH

before_install:
  - pip install --user awscli
  - mkdir -p ~/test-site
  - touch ~/test-site/test-file
  - aws s3 sync ~/test-site s3://$S3_BUCKET/test-site
  - mkdir -p ~/site

jobs:
  include:
  - stage: run-ank
    script:
    - ./gradlew clean build > build.log
    - ./gradlew dokka :arrow-docs:runAnk > run_ank.log
    - aws s3 sync modules/docs/arrow-docs/build/site s3://$S3_BUCKET/site > aws_sync_ank.log1
#  - stage: deploy
#    script:
#    - ./gradlew codeCoverageReport
#    - bash <(curl -s https://codecov.io/bash)
#    - ./deploy-scripts/deploy.sh
  - stage: deploy-docs
    script:
    - rvm use 2.5.3 --install --fuzzy
    - gem install jekyll -v 3.7.4
    - aws s3 sync s3://$S3_BUCKET/site ~/site > aws_sync_jekyll.log
    - jekyll build -s ~/site -d ~/_site
    - aws s3 sync ~/_site s3://$S3_BUCKET > aws_sync_site.log
