version: 2
jobs:
  dokka:
    docker:
    - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx4g
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    working_directory: ~/arrow
    steps:
    - checkout
    - run: sudo cat /proc/meminfo
    - run: java -XX:+PrintFlagsFinal -version | grep HeapSize
    - run: sudo chmod +x ./gradlew
    - run:
        name: Run dokka
        command: ./gradlew dokka
  ank:
    docker:
    - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx4g
      GRADLE_OPTS: -Dorg.gradle.daemon=false
    working_directory: ~/arrow
    steps:
    - run:
        name: Run Ank if dokka pass and branch is not Master
        command: ./gradlew :arrow-docs:runAnk
  ank-master:
    docker:
    - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx4g
    working_directory: ~/arrow
    steps:
    - run:
        name: Run Ank if dokka pass and branch is Master
        command: ./gradlew :arrow-docs:runAnk

workflows:
  version: 2
  build-docs:
    jobs:
    - dokka
    - ank:
        requires:
        - dokka
        filters:
          branches:
            ignore: master
    - ank-master:
        requires:
        - dokka
        filters:
          branches:
            only: master