version: 2
jobs:
  dokka:
    docker:
    - image: - image: circleci/openjdk:8-jdk-browsers
    environment:
      JVM_OPTS: -Xmx3200m
    working_directory: ~/arrow
    steps:
    - checkout
    - run: pwd
    - run: ls
    - run: gradle test
    - run:
        name: Run dokka
        command: ./gradlew dokka
  ank:
    docker:
    - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx4g
    working_directory: ~/arrow
    steps:
    - run:
        name: Run Ank if dokka pass and branch is not Master
        command: ./gradlew :arrow-docs:runAnk
  ank-master:
    docker:
    - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx4g
    working_directory: ~/arrow
    steps:
    - run:
        name: Run Ank if dokka pass and branch is Master
        command: ./gradlew :arrow-docs:runAnk

workflows:
  version: 2
  build-docs:
    jobs:
    - dokka
    - ank:
        requires:
        - dokka
        filters:
          branches:
            ignore: master
    - ank-master:
        requires:
        - dokka
        filters:
          branches:
            only: master