version: 2
jobs:
  dokka:
    docker:
    - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    working_directory: ~/arrow
    steps:
    - checkout
    - restore_cache:
      key: gradle-{{ checksum "build.gradle" }}-{{ checksum  "buildSrc/src/main/java/Dependencies.kt" }}
    - run:
        name: Download Dependencies
        command: ./gradlew checkDependenciesVersion
    - save_cache:
        paths:
        - ~/.gradle
        key: gradle-{{ checksum "build.gradle" }}-{{ checksum  "buildSrc/src/main/java/Dependencies.kt" }}
    - run:
        name: Run dokka
        command: ./gradlew dokka
  ank:
    docker:
    - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx4g
    working_directory: ~/arrow
    steps:
    - run:
        name: Run Ank if dokka pass and branch is not Master
        command: ./gradlew :arrow-docs:runAnk
  ank-master:
    docker:
    - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx4g
    working_directory: ~/arrow
    steps:
    - run:
        name: Run Ank if dokka pass and branch is Master
        command: ./gradlew :arrow-docs:runAnk

workflows:
  version: 2
  build-docs:
    jobs:
    - dokka
    - ank:
        requires:
        - dokka
        filters:
          branches:
            ignore: master
    - ank-master:
        requires:
        - dokka
        filters:
          branches:
            only: master