version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx4g
    working_directory: ~/arrow
    steps:
    - checkout
    - run:
        name: Build
        command: ./gradlew clean build --no-daemon
  dokka:
    docker:
    - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx4g
    working_directory: ~/arrow
    steps:
    - run:
        name: Run dokka
        command: ./gradlew dokka --no-daemon
  ank:
    docker:
    - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx4g
    working_directory: ~/arrow
    steps:
    - run:
        name: Run Ank if dokka pass and branch is not Master
        command: ./gradlew :arrow-docs:runAnk --no-daemon
  ank-master:
    docker:
    - image: circleci/openjdk:8-jdk
    environment:
      JVM_OPTS: -Xmx4g
    working_directory: ~/arrow
    steps:
    - run:
        name: Run Ank if dokka pass and branch is Master
        command: ./gradlew :arrow-docs:runAnk --no-daemon

workflows:
  version: 2
  build-docs:
    jobs:
    - build
    - dokka:
        requires:
        - build
    - ank:
        requires:
        - dokka
        filters:
          branches:
            ignore: master
    - ank-master:
        requires:
        - dokka
        filters:
          branches:
            only: master